### ISSUE TITLE
Make repo open-source

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/anon#2]
This is a nice piece of open-source-able functionality.

What needs to be done?
- [x] Remove `@reevoo.com` from code
- [x] Add specs
- [x] Improve CLI code for extensibility
- [x] Gemify (#1)
- [x] Documentation Review
- [x] Comment Review

**Comment by errm** [comment]
Looks done

**Comment by reneklacan** [comment]
README needs update as CLI interface changed
